-- Manual customer emails from the admin Orders tab. Status changes no longer
-- email the customer automatically; instead the admin writes (or edits a
-- status template) and sends a message through the send-order-email Edge
-- Function. Every attempt is logged here — sent or failed — so the order
-- detail view shows exactly what the customer was told and when.
-- Written by the service role only (same pattern as order_status_history).

create table if not exists order_emails (
  id        bigint generated by default as identity primary key,
  order_id  uuid references orders(id) on delete cascade,
  to_email  text not null,
  subject   text not null,
  body      text not null,
  status    text not null default 'sent',   -- 'sent' | 'failed'
  error     text,
  sent_at   timestamptz not null default now()
);

alter table order_emails enable row level security;

drop policy if exists "order_emails admin read" on order_emails;
create policy "order_emails admin read" on order_emails for select using (is_admin());
-- No insert/update/delete policy for anon/authenticated — only the service
-- role (inside send-order-email) can write rows.

create index if not exists order_emails_order_id_idx on order_emails (order_id);
