-- Adds an audit trail for order status changes and a dedup guard for the
-- "status changed" customer email sent by the new update-order-status Edge
-- Function. Written by the service role only (same pattern as `transactions`
-- in add-order-extras.sql) — the admin panel never writes this table
-- directly, so every row here reflects a real, server-recorded change.

create table if not exists order_status_history (
  id         bigint generated by default as identity primary key,
  order_id   uuid references orders(id) on delete cascade,
  status     text not null,
  changed_at timestamptz not null default now(),
  notified   boolean not null default false
);

alter table order_status_history enable row level security;

create policy "order_status_history admin read" on order_status_history for select using (is_admin());
-- No insert/update/delete policy for anon/authenticated — only the service
-- role (used inside update-order-status) can write rows.

create index if not exists order_status_history_order_id_idx on order_status_history (order_id);
