-- Adds a transaction audit log, a way to tell test payments apart from real
-- orders (used by the admin test-payment tool), and the plumbing to send
-- exactly one confirmation email per order.

alter table orders add column if not exists is_test boolean not null default false;

create table if not exists transactions (
  id              bigint generated by default as identity primary key,
  order_id        uuid references orders(id) on delete cascade,
  provider        text not null,          -- 'takbull' (only gateway in use)
  provider_txn_id text,
  status          text not null,          -- 'succeeded' | 'failed'
  amount          numeric not null default 0,
  currency        text not null default 'ILS',
  raw             jsonb,
  created_at      timestamptz default now()
);

alter table transactions enable row level security;

create policy "transactions admin read" on transactions for select using (is_admin());
-- No insert/update/delete policy for anon/authenticated — only the service
-- role (used inside the webhook/IPN Edge Functions) can write rows.

create index if not exists transactions_order_id_idx on transactions (order_id);
