-- Sign-up pop-up + 5% coupon system. Coupons carry PII (email/phone), so
-- unlike most tables here there is NO client-facing RLS policy at all --
-- every read/write goes through a service-role Edge Function
-- (signup-coupon, validate-coupon, admin-coupons), never a direct
-- sb.from("coupons") call from the browser.

create table if not exists coupons (
  id          bigint generated by default as identity primary key,
  code        text not null unique,
  name        text,
  email       text not null,
  phone       text,
  percent     numeric not null default 5,      -- snapshot of content.signupCouponPercent at issue time
  status      text not null default 'active',  -- 'active' | 'redeemed' | 'void'
  order_id    uuid references orders(id),
  redeemed_at timestamptz,
  expires_at  timestamptz,                      -- null = no expiry (not currently offered in the UI)
  created_at  timestamptz default now()
);

alter table coupons enable row level security;
-- Intentionally no policies -- anon/authenticated get zero direct access.

create index if not exists coupons_code_idx on coupons (code);
create index if not exists coupons_email_idx on coupons (email);

alter table orders add column if not exists coupon_code text;
alter table orders add column if not exists discount numeric not null default 0;
