-- =============================================================================
--  ALFI · Database schema  (PostgreSQL / Supabase)
--  Run this in the Supabase SQL editor (or any Postgres), then set
--  CONFIG.BACKEND = 'supabase' in store-api.js and paste your URL + anon key.
-- =============================================================================

-- ---------- PRODUCTS ----------------------------------------------------------
create table if not exists products (
  id          bigint generated by default as identity primary key,
  name        text    not null default '',
  category    text    not null default 'טבעות',
  price       numeric not null default 0,
  material    text    not null default 'כסף 925',
  description text    not null default '',
  image       text    not null default '',     -- URL or data-URL
  sizes       text[]  not null default '{S,M,L}',
  featured    boolean not null default false,
  created_at  timestamptz default now()
);

-- ---------- SITE CONTENT (single editable row) --------------------------------
create table if not exists content (
  id    int primary key default 1,
  data  jsonb not null default '{}'::jsonb,
  check (id = 1)
);
insert into content (id, data) values (1, '{}'::jsonb) on conflict (id) do nothing;

-- ---------- COLLECTIONS -------------------------------------------------------
create table if not exists collections (
  id          bigint generated by default as identity primary key,
  title       text not null default '',
  subtitle    text not null default '',
  description text not null default '',
  image       text not null default '',
  created_at  timestamptz default now()
);

-- ---------- PROFILES (extends Supabase auth.users) ----------------------------
create table if not exists profiles (
  id         uuid primary key references auth.users(id) on delete cascade,
  name       text,
  email      text,
  role       text default 'customer',   -- 'customer' | 'admin'
  created_at timestamptz default now()
);

-- Auto-create a profile row whenever a user signs up
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, name, email, role)
  values (new.id, new.raw_user_meta_data->>'name', new.email,
          coalesce(new.raw_user_meta_data->>'role','customer'))
  on conflict (id) do nothing;
  return new;
exception when others then
  return new;   -- never block signup if the profile insert hiccups
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users for each row execute function public.handle_new_user();

-- ---------- ORDERS ------------------------------------------------------------
create table if not exists orders (
  id               uuid primary key default gen_random_uuid(),
  number           text,
  user_id          uuid references auth.users(id),
  items            jsonb   not null default '[]'::jsonb,  -- [{id,name,qty,price,size}]
  subtotal         numeric not null default 0,
  shipping         numeric not null default 0,
  total            numeric not null default 0,
  status           text    not null default 'התקבלה',
  shipping_address jsonb,
  created_at       timestamptz default now()
);

-- ---------- ROW LEVEL SECURITY ------------------------------------------------
alter table products enable row level security;
alter table collections enable row level security;
alter table content  enable row level security;
alter table orders   enable row level security;
alter table profiles enable row level security;

-- helper: is the current user an admin?
create or replace function is_admin() returns boolean as $$
  select exists (select 1 from profiles where id = auth.uid() and role = 'admin');
$$ language sql stable security definer;

-- Products & content: everyone reads, only admins write
create policy "products read"  on products for select using (true);
create policy "products write" on products for all    using (is_admin()) with check (is_admin());
create policy "content read"   on content  for select using (true);
create policy "content write"  on content  for all    using (is_admin()) with check (is_admin());
create policy "collections read"  on collections for select using (true);
create policy "collections write" on collections for all    using (is_admin()) with check (is_admin());

-- Orders: a user sees/creates their own; admins see all
create policy "orders own read"   on orders for select using (auth.uid() = user_id or is_admin());
create policy "orders own insert" on orders for insert with check (auth.uid() = user_id);
create policy "orders admin write" on orders for update using (is_admin()) with check (is_admin());

-- Profiles: a user reads/updates their own; admins read all
create policy "profiles own"   on profiles for all    using (auth.uid() = id) with check (auth.uid() = id);
create policy "profiles admin" on profiles for select using (is_admin());

-- ---------- SEED PRODUCTS -----------------------------------------------------
insert into products (name, category, price, material, description, featured, sizes) values
  ('טבעת ורד',    'טבעות',   480, 'כסף 925',       'טבעת כסף 925 בעיצוב עלי כותרת עדינים הנפתחים סביב האצבע.', true,  '{S,M,L,XL}'),
  ('שרשרת פריחה', 'שרשראות', 620, 'כסף 925',       'תליון פרח כסף על שרשרת חוליות עדינה. אורך מתכוונן.',        true,  '{"40 ס\"מ","45 ס\"מ","50 ס\"מ"}'),
  ('עגילי יסמין', 'עגילים',  340, 'כסף 925',       'עגילי תליה קלילים בצורת ניצן יסמין.',                       true,  '{יחיד}'),
  ('צמיד גן',     'צמידים',  560, 'כסף 925',       'צמיד חוליות עם פרחי כסף זעירים משובצים לאורכו.',           true,  '{S,M,L}'),
  ('טבעת עלה',    'טבעות',   390, 'כסף 925',       'עלה כסף מעודן הכורך את האצבע בקו אורגני ורך.',             false, '{S,M,L,XL}'),
  ('שרשרת לבנדר', 'שרשראות', 720, 'כסף + זירקון',  'מחרוזת ענפי לבנדר מכסף עם שיבוץ זירקון עדין.',             false, '{"40 ס\"מ","45 ס\"מ"}'),
  ('עגילי כלנית', 'עגילים',  420, 'כסף 925',       'עגילי צמוד בצורת כלנית פורחת, עם מרכז מלוטש מבריק.',       false, '{יחיד}'),
  ('צמיד שזיף',   'צמידים',  680, 'כסף מוזהב',     'צמיד נוקשה דק עם פריחת שזיף חרוטה, אלגנטי וקליל.',         false, '{S,M,L}')
on conflict do nothing;

-- ---------- SEED COLLECTIONS --------------------------------------------------
insert into collections (title, subtitle, description) values
  ('פריחת אביב', 'הקולקציה החדשה', 'תכשיטים בהשראת פריחת השדה — קלילים, צבעוניים ומלאי חיים.'),
  ('כלות', 'ליום המיוחד', 'עדינות זוהרת לכלה ולמלוות — כסף סטרלינג עם נצנוץ זירקון.'),
  ('מתנות', 'לרגעים קטנים', 'תכשיט שאומר הכל, גם בלי מילים. ארוז ומוכן למסירה.')
on conflict do nothing;

-- ---------- STORAGE BUCKET (product / banner images) -------------------------
-- Public bucket so images display to everyone; only admins can upload/change.
insert into storage.buckets (id, name, public)
  values ('product-images', 'product-images', true)
  on conflict (id) do nothing;

drop policy if exists "images public read"   on storage.objects;
drop policy if exists "images admin insert"  on storage.objects;
drop policy if exists "images admin update"  on storage.objects;
drop policy if exists "images admin delete"  on storage.objects;

create policy "images public read"  on storage.objects
  for select using (bucket_id = 'product-images');
create policy "images admin insert" on storage.objects
  for insert with check (bucket_id = 'product-images' and is_admin());
create policy "images admin update" on storage.objects
  for update using (bucket_id = 'product-images' and is_admin());
create policy "images admin delete" on storage.objects
  for delete using (bucket_id = 'product-images' and is_admin());

-- ---------- MAKE YOURSELF ADMIN ----------------------------------------------
-- After you sign up through the site, run (with your email):
--   update profiles set role = 'admin' where email = 'you@example.com';
